### ISSUE TITLE
for instead of "to to"

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-router-nested-routes-code-along#10]
In this sentence, change "to to" to "for":

"In order to to MovieShow to display this content,"

Thank you.

**Comment by atxrenegade** [comment]
"In order to to MovieShow to display this content, we will need make our movies collection available within MovieShow:"

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore and @atxrenegade,

Thank you for spotting these issues. These errors have been fixed based on your feedback. Thank you for contributing!
