### ISSUE TITLE
Missing "the"

### ISSUE THREAD

**Issue by RylanBauermeister** [learn-co-curriculum/react-router-nested-routes-code-along#11]
"It is simply middle component between App and MoviesList, but we will come back to this component in a moment."

should read:

"It is simply **the** middle component between App and MoviesList, but we will come back to this component in a moment."

**Comment by maxwellbenton** [comment]
Hi @RylanBauermeister,

Thank you for spotting this. This typo has been fixed based on your feedback.

Thanks for contributing!
