### ISSUE TITLE
Paths shown in example code blocks for MovieShow do not match

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/react-router-nested-routes-code-along#13]
While doing this code along I got an error when I got to the step shown in the screenshot below.

```
Failed to compile.

./src/components/MovieShow.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/jeremiah/Development/code/react-router-nested-routes-code-along-online-web-ft-061019/src/components/MovieShow.js'
```

Upon further review, I found that the paths were not the same in the code blocks shown.  Once I moved MovieShow.js to the `components` folder, then it worked fine.  

![Learn - Nested Routes Code Along 2019-10-28 09-22-04](https://user-images.githubusercontent.com/39208179/67691723-aca43800-f964-11e9-9f12-949e074c36be.png)

**Comment by maxwellbenton** [comment]
Hi @jrodden1,

Thank you for pointing this out! We've updated the code snippet comment to say components rather than containers so this issue should now be resolved
