### ISSUE TITLE
MovieShow Component Does Not Have The routerProps Passed To It

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/react-router-nested-routes-code-along#3]
Under the final section "Linking to the Show", the lab mentions that the MovieShow will require the `routerProps` to work correctly, but in the code example they are not actually passed down to the component.

This line:

```
<Route path={`${match.url}/:movieId`} render={routerProps => <MovieShow movies={movies} /> } />
```

Needs to be replaced with this:

```
<Route path={`${match.url}/:movieId`} render={routerProps => <MovieShow {...routerProps} movies={movies} /> } />
```

This is located in the second-to-last code example of the lab.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by kostanzhoglo** [comment]
Thanks for notifying me about this, and for fixing the line of code!

Glad others won't run into the same thing.

Best,
J
