### ISSUE TITLE
Missing all solution components

### ISSUE THREAD

**Issue by karsonkalt** [learn-co-curriculum/react-router-nested-routes-code-along#37]
## Describe the bug
The solution branch does not have all the components needed to solve the lab. I have tried checking my solution against the solution but the proper components are not part of the repo.

**Comment by ihollander** [comment]
Thanks for flagging this @karsonkalt! I updated the solution branch to include the missing components. https://github.com/learn-co-curriculum/react-router-nested-routes-code-along/pull/38
