### ISSUE TITLE
Check MovieShow Component

### ISSUE THREAD

**Issue by lawrend** [learn-co-curriculum/react-router-nested-routes-code-along#4]
Everything works on the code along until the final mod of MovieShow. Throws error that 'match' is undefined. It's not being passed as an explicit prop but error isn't resolved by doing so. I see the file was updated to fix a typo recently and not many have worked the lab since so a typo might still exist? 

And apologies if this is a student-side error :)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
